version: '3'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "4002:4002"
    networks:
      - npm_network

networks:
  npm_network:
      name: npm_network
